In [51]:
import pandas as pd
import numpy as np
import math

In [36]:
ds = pd.read_csv("Iris.csv")
ds2 = ds[["SepalWidthCm","PetalLengthCm","SepalLengthCm","PetalWidthCm"]].to_numpy()
df = ds[["SepalLengthCm"]].to_numpy()

In [37]:
ds.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [44]:
def mean(column):
    sum = 0
    #count = 0
    for i in column:
        sum += i
        #count += 1
    return sum/len(column);

In [111]:
avg = mean(df)
avg

array([5.84333333])

In [72]:
def median(column):
    a = np.sort(column,axis=0)
    #print(a)
    x = a[math.floor(len(a)/2)] + a[math.ceil(len(a)/2)]
    return x/2
        

In [73]:
median(df)

array([5.8])

In [89]:
def mode(column):
    a = np.sort(column,axis=0)
    #print(a)
    m = 0
    count = 0
    for i in range(len(a)-1):
        if a[i] == a[i+1]:
            count += 1
        elif a[i] != a[i+1]:
            count = 0
        if count>m:
            m = count;
            ind = i;
    return a[ind]

In [90]:
mode(df)

array([5.])

In [91]:
def variance(column):
    m = mean(column)
    x = 0
    for i in column:
        a = (m - i)
        x += pow(a,2)
    return x/len(column)

In [92]:
variance(df)

array([0.68112222])

In [93]:
def SD(column):
    return pow(variance(column),1/2)

In [94]:
SD(df)

array([0.82530129])

In [95]:
def CoV(column):
    return SD(column)/mean(column)

In [97]:
CoV(df)

array([0.1412381])

In [112]:
def quartile(column):
    a = np.sort(column, axis=0)
    q1 = a[math.floor(len(a)/4)] + a[math.ceil(len(a)/4)]
    q2 = a[math.floor(len(a)/2)] + a[math.ceil(len(a)/2)]
    q3 = a[math.floor(3*len(a)/4)] + a[math.ceil(3*len(a)/4)]
    return[q1/2,q2/2,q3/2, (q3-q1)/4]

In [113]:
quartile(df)

[array([5.1]), array([5.8]), array([6.4]), array([0.65])]

In [109]:
def skewness(column):
    return 3*(mean(column) - median(column))/SD(column)

In [110]:
skewness(df)

array([0.15751823])